---
title: "Calyx Baseline Model"
author: "Brandon Clark"
format: dashboard
---
```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(readxl)
library(jsonlite)
#install.packages("DT")
library(DT)
library(shiny)
library(scales)
theme_set(theme_bw(base_size = 22))
```


```{r}
#| label: get data
#| message: false
baselines <- read_excel("/Users/brandonclark/Desktop/Calyx_ProjectRasters/Copy of VM0048 project list - R.xlsx", sheet = 2)

baselines <- baselines |>
  rename(project_area = `Project area`)|>
  rename(nonVM48 = `Non-VM48 deforestation baseline`)|>
  rename(verra_average = `Verra Average`)
baselines$nonVM48[19]<- 1772
baselines$nonVM48[28]<- 3365
baselines <- baselines|>
  mutate(nonVM48_rate = (nonVM48 / project_area) * 100)|>
  mutate(verra_average_rate = (verra_average / project_area) * 100)|>
  mutate(rate_diff = (nonVM48_rate - verra_average_rate))|>
  mutate(baseline_status = if_else(rate_diff > 0,
            "overestimated",
            "underestimated"))

avg_diff <- baselines |>
  group_by(Jurisdiction) |>
  summarize(avg_rate_diff = mean(rate_diff, na.rm = TRUE))


 num_projects <- n_distinct(baselines$`Project ID`)
 projects_over <- sum(baselines$rate_diff > 0)
 projects_under <- sum(baselines$rate_diff < 0)
 smallest_proj <- min(baselines$project_area)
 largest_proj <- max(baselines$project_area)
 min_rate_diff <-min(baselines$rate_diff)
 max_rate_diff <- max(baselines$rate_diff)
```

## Row {height=150px}

### Column 

```{r}
#| content: valuebox
#| title: Number of Projects

list(color = "primary",
     value = num_projects)
```

### Column
```{r}
#| content: valuebox
#| title: Overestimated Projects

list(color = "danger",
     value = projects_over)
```
### Column
```{r}
#| content: valuebox
#| title: Underestimated Projects

list(color = "primary",
     value = projects_under)
```
### Column
```{r}
#| content: valuebox
#| title: Smallest Rate Difference (old - new)

list(color = "primary",
     value = min_rate_diff)

```
### Column
```{r}
#| content: valuebox
#| title: Largest Rate Difference (old - new)

list(color = "danger",
     value = max_rate_diff)
```
## Row {height="20%"}

### Column 
```{r}
#| title: "Scatter plot of old vs VM48 baseline"
ggplot(baselines, aes(x = verra_average_rate,
               y = nonVM48_rate,
               size = project_area,
               color = baseline_status)) +
  
  geom_point(alpha = 0.3) +
  
  # 1:1 line
  geom_abline(slope = 1, intercept = 0,
              linewidth = 0.75) +
  
  scale_color_manual(values = c(
    "overestimated" = "dodgerblue",
    "underestimated" = "forestgreen"
  )) +
  
  scale_x_continuous(labels = label_percent(scale = 1))+
scale_y_continuous(labels = label_percent(scale = 1)) +
  scale_size_continuous(name = "Project Area",labels = scales::comma
  )+
  labs(title = "VM0048 Baseline Comparison",
    x = "VM0048 Baseline Rate",
    y = "Old Baseline Rate",
    color = NULL,
    size = "Project Area (ha)"
  ) +
  
  theme_minimal(base_size = 14)


```
### Column
```{r}
#| title: "Bar graph of average rate difference by jurisdiction"

ggplot(avg_diff,
  aes(x = Jurisdiction,
  y = avg_rate_diff))+
  geom_col()+
  geom_text(
    aes(label = round(avg_rate_diff, 2)),
    vjust = -1,
    size = 4.5)+
  theme_minimal()+
  labs(title = "Average Deforestation Baseline Rate Difference by Jurisdiction",
       y = "Rate difference average")
```


